### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by qeelex** [workofart/brawlstars-ai#2]
Hello could you please explain how to start it i dont understand it how to make it work where to start it etc. 
I would like you to add me in discord and help me Mafk#2544.
Mafk

**Comment by workofart** [comment]
Hi @qeelex, thanks for the question. Unfortunately, as stated in the description of the project, I'm no longer maintaining this project because Brawlstars client has been constantly updating. This project was based on an old client version 16.176, but it's impossible to run it now when the latest version is 44.242 (as of 2022/08/20), because the game will validate the version and force you to update. I will make it clear in the README file so others would have the correct expectations. 

Other ways this project might be helpful:
- provide an example of how to apply computer vision and reinforcement learning in real world applications from scratch (you can read my blog post [[1](https://www.henrypan.com/blog/2019-04-20-Brawlstars-AI/), [2](https://www.henrypan.com/blog/2019-04-25-Brawlstars-RL/)] to follow along without actually running the project yourself)
- provide an example of how to control an android simulator programmatically using Python
- presents common pitfalls of computer vision and reinforcement learning in real life

Hope this helps 😄 
p.s. I'm closing this issue because it's not going to be addressed.
